# fly.toml app configuration file generated for esty-bulk-discounts on 2023-08-07T15:26:06-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "esty-bulk-discounts"
primary_region = "den"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare csv_load:all"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
